version: "3.1"

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hb_student_tracker
      MYSQL_USER: hbstudent
      MYSQL_PASSWORD: admin
    volumes:
      - "$PWD/data/mysql:/var/lib/mysql"
      - "$PWD/scripts/mysql:/docker-entrypoint-initdb.d"